### PR TITLE
Chore: Added LICENSE

### LINKED ISSUE #1: Add LICENSE
Add license for the repository

### PR DESCRIPTION
**Pull request by Kaushik080**
This pr Fixes: #1 
Added License to the repository

### CODE REVIEW

**Comment by Kaushik080** [comment]
@antirez please check

**Comment by ArjixWasTaken** [comment]
What made you think that the GPL licence is the one that should be used?
If you actually read the licence included with the code, it is a copy of the licence that Redis has, and Redis claims that it is a BSD licence.

https://redis.io/docs/about/license/

Heck, the licence text protects Redis' trademark, probably a copy/paste mistake.

**Comment by Kaushik080** [comment]
I used GPLv3 because it states that if you modify and distribute GPLv3-licensed code, you must share those modifications as open source, preventing the creation of closed-source versions, thus preserving the software's open nature.

**Comment by antirez** [comment]
The program already has a license in the top comment of smallchat.c file. Removing the "Redis" name from it that is indeed cut&paste error :)

**Pull request closed without merging**
